
# Save this file with a .ps1 extension and run it in PowerShell, not in a Unix shell

New-Item -ItemType Directory -Force -Path "C:\Users\ADMIN\index.html\pexelsImages"
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.jpg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.png" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.gif" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.webp" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.jpeg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.avif" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.svg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.webm" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.mp4" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.mp3" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.wav" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.ogg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.flac" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.aac" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.opus" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.mkv" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.avi" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.mov" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.flv" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.m4a" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.m4v" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.ts" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.m3u8" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.json" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.txt" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.xml" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
# The following line tries to move a directory to a file, which will fail. Remove or correct as needed:
# Move-Item "C:\Users\ADMIN\index.html\pexelsImages" "C:\Users\ADMIN\index.html\PexelsImagesGallery.jsx"
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.css" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.js" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.html" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.php" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.md" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.yaml" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.yml" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.csv" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.tsv" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.log" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.zip" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.rar" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.tar" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.gz" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.7z" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.exe" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.dll" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.so" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.bin" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.apk" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.ipa" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.dmg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.iso" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.pkg" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.deb" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.rpm" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.msi" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.psd" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.ai" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.eps" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.svgz" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.woff" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.woff2" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.ttf" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.otf" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.eot" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.jsonld" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.md5" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.sha256" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.sha512" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.meta" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.info" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.resume" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.dht" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.peers" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.tracker" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.files" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_length" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hash" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_size" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_count" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_index" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_offset" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_length" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hashes" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hashes_v2" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hashes_v3" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hashes_v4" "C:\Users\ADMIN\index.html\pexelsImages\" -Force
Move-Item "C:\Users\ADMIN\index.html\pexelsImages\pexels-*.torrent.piece_hashes_v5" "C:\Users\ADMIN\index.html\pexelsImages\" -Force