name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # LTS and current stable versions
        # See Node.js release schedule: https://nodejs.org/en/about/releases/

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"  # Cache based on lockfile
          registry-url: "https://registry.npmjs.org"       # Optional: Default npm registry
          scope: "@your-scope"                            # Optional: For private scoped packages

      # Install dependencies
      - run: npm ci

      # Build (if `build` script exists)
      - run: npm run build --if-present

      # Run tests
      - run: npm test

      # (Optional) Upload test results
      - name: Upload test results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/**/*
            coverage/
